name: Deploy to Azure

on:
  push:
    branches:
      - main  # Trigger on commit to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Build the project (assuming React/Vue/Angular, etc.)
      - name: Build project
        run: |
          npm run build

      # Step 5: Log into Azure using service principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          app-id: ${{ secrets.AZURE_APP_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          password: ${{ secrets.AZURE_PASSWORD }}

      # Step 6: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}  
          package: ./build  # Point to the build directory
